name: clean_architecture
description: An architecture and widgets for an MVVM inspired architecture in
  Flutter. It provides common functionalities required to build a large
  application in a understandable manner.

version: 1.1.1+1


environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.4 #7.1.3
  meta: ^1.3.0
  provider: ^6.0.0 #5.0.0
  collection: ^1.15.0
  dio: ^4.0.4
  freezed_annotation: ^2.2.0
  freezed: ^2.3.0
  equatable: ^2.0.5


  #universal_io
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
